name: Deploy Static Site with Nginx

on:
  push:
    branches:
      - master

jobs:
  setup-nginx:
    name: Setup Nginx
    runs-on: self-hosted

    steps:
      - name: Install Nginx
        run: |
          sudo apt update
          sudo apt install -y nginx

      - name: Start and Enable Nginx
        run: |
          sudo systemctl enable nginx
          sudo systemctl start nginx

  deploy-files:
    name: Deploy Static Files
    runs-on: self-hosted
    needs: setup-nginx

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Repository Files (for debugging)
        run: ls -la

      - name: Copy HTML and CSS to Nginx Directory
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp index.html /var/www/html/
          sudo cp styles.css /var/www/html/
          sudo systemctl reload nginx

  install-docker:
    name: Install and Start Docker
    runs-on: self-hosted
    needs: deploy-files

    steps:
      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Start and Enable Docker
        run: |
          sudo systemctl enable docker
          sudo systemctl start docker
          
  install-maven:
   name: Install Maven
   runs-on: self-hosted
   needs: deploy-files

   steps:
    - name: Update APT and Install Maven
      run: |
        sudo apt update
        sudo apt install -y maven

